### PR TITLE
Update to pybind 2.5.0

### PR DESCRIPTION
**Pull request by mabelzhang**
The update gets rid of compiler warnings on macOS and Windows for packages depending on `pybind11_vendor`.

There is a compiler warning on macOS about unused declared variable `CMAKE_C_COMPILER`. Can we remove that line?

macOS
Before: http://ci.ros2.org/job/ci_osx/9530/
After: http://ci.ros2.org/job/ci_osx/9544/

Windows
Before: http://ci.ros2.org/job/ci_windows/11627/
After: http://ci.ros2.org/job/ci_windows/11645/

Signed-off-by: Mabel Zhang <mabel@openrobotics.org>

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM

I guess it's safe to remove the CMAKE_C_COMPILER arg. @mjcarroll Can you think of any reason not to?

**Comment by mjcarroll** [comment]
> Can you think of any reason not to?

No objections here.

**Comment by mabelzhang** [comment]
CI passing. Merging.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11717/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6805/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9559/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11658/)

**Comment by mabelzhang** [comment]
Actually, I have no permission in this repo to merge. Can someone merge this?

**Comment by jacobperron** [comment]
> I have no permission in this repo to merge

I've given the team access for future.

**Pull request merged**
