### PR TITLE
Update vendored package to pybind11 2.9.1

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This appears to be necessary for python_orocos_kdl_vendor.
When forcing the vendor package to build pybind11 prior to this change the following error is present:

    -- pybind11 found, building against installed version
    CMake Error at /home/jenkins-agent/workspace/ci_linux/ws/install/pybind11_vendor/share/cmake/pybind11/pybind11NewTools.cmake:196 (python3_add_library):
      Unknown CMake command "python3_add_library".
    Call Stack (most recent call first):
      /home/jenkins-agent/workspace/ci_linux/ws/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/CMakeLists.txt:60 (pybind11_add_module)

    -- Configuring incomplete, errors occurred!
    See also "/home/jenkins-agent/workspace/ci_linux/ws/build/python_orocos_kdl_vendor/CMakeFiles/CMakeOutput.log".

The patch from 2.7.1 didn't apply cleanly.
This patch was generated from v2.9.1 after manually creating the changes using the following command:

    git format-patch v2.9.1 --minimal --stdout | \
    awk '/^diff/ { start = 1 } start { if ($0 ~ /^-- $/){ exit(0)}; print $0 }'

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
CI just demonstrating the build failure by building rclpy and python_orocos_kdl_vendor

Before: [Build Status](https://ci.ros2.org/job/ci_linux/16560/)

After: [Build Status](https://ci.ros2.org/job/ci_linux/16563/)

**Review by clalancette — COMMENTED** [review]
This is generally good, and matches the version that Jammy has.  It looks like CI is unhappy, though that may be our general Windows unhappiness at the moment.

**Comment by nuclearsandwich** [comment]
> This is generally good, and matches the version that Jammy has. It looks like CI is unhappy, though that may be our general Windows unhappiness at the moment.

These builds are running on Linux with FORCE_BUILD_VENDOR_PKG=ON. I actually first started investigating this for Space ROS where we're building ROS 2 from source using Rolling branches on Focal and figured that it had to do with the vendored pybind11 version being insufficient. But the build above demonstrates that I get the same failure with both pybind11 2.9.1 and 2.7.1.

I think this change is worth making regardless as it gets us onto Jammy's current pybind11 version but I have to keep digging on what's causing this specific failure.

**Comment by nuclearsandwich** [comment]
Since we may want to get this in before the Humble branch... Full CI above pybind11_vendor

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16565/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11149/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16951/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/16952/)

**Comment by nuclearsandwich** [comment]
There's actually a cleaner version of the patch file contents which I haven't yet merged.

**Review by audrow — APPROVED** [review]
Looks good to me!

**Review by clalancette — APPROVED** [review]
It also looks good to me.

**Pull request merged**
