### PR TITLE
Fix Windows CI warning

### PR DESCRIPTION
**Pull request by mabelzhang**
Added CMake args to try to fix the Windows CI warning mentioned here https://github.com/ros2/ros2/pull/996#issuecomment-668117566

Signed-off-by: Mabel Zhang <mabel@openrobotics.org>

### CODE REVIEW

**Comment by mabelzhang** [comment]
I'm running Windows CI on this package, but I don't know if that would expose the warning - in #2, there were no warnings with these parameters.

Maybe I should run one that tests all packages?

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11688/)

**Comment by dirk-thomas** [comment]
> I'm running Windows CI on this package, but I don't know if that would expose the warning - in #2, there were no warnings with these parameters.

You can run the same build without the patch from this PR to confirm that the warning appears before.

**Comment by mabelzhang** [comment]
The weird thing is that it actually didn't appear before, when we merged the PR that caused the failure.

Here it is again on `master`:
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11689/)

**Comment by mabelzhang** [comment]
Ooh @hidmic said Windows nightlies use CMAKE_BUILD_TYPE `Release`, which should expose the warning. Regular CI defaults to `None`.

Without patch:
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11690/)

With patch:
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11691/)

**Comment by mabelzhang** [comment]
The failed build was complaining about a `C:\Program` path from a generated file:
```
14:39:40   CMake Error at pybind11-2.5.0-stamp/download-pybind11-2.5.0.cmake:106 (message):
14:39:40     Syntax error in cmake code at
14:39:40       C:/ci/ws/build/pybind11_vendor/pybind11-2.5.0-prefix/src/pybind11-2.5.0-stamp/download-pybind11-2.5.0.cmake:108
14:39:40     when parsing string
14:39:40       C:\Program
14:39:40     Invalid character escape '\P'.
```

It's not clear where that path comes from. @hidmic suggested it looks like some paths were not converted correctly to CMake paths.

Suppressing warnings on Windows instead:
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11693/)

**Comment by mabelzhang** [comment]
@dirk-thomas CI is green now.
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11696/)

The fix was just to not define `CMAKE_BUILD_TYPE`, which was unused for Windows.

**Comment by dirk-thomas** [comment]
> The fix was just to not define `CMAKE_BUILD_TYPE`, which was unused for Windows.

I don't understand the current patch. `pybind11` will then always be built with the default build type (decided by `pybind11` CMake logic and doesn't honor the selected `CMAKE_BUILD_TYPE`?

**Comment by mabelzhang** [comment]
Good point. For some reason Windows is saying that variable is unused. That is the original warning:
```
14:38:02     Manually-specified variables were not used by the project:
14:38:02       CMAKE_BUILD_TYPE
```
Maybe pybind is ignoring it. Seems weird. pybind's `CMakeLists.txt` between 2.2.4 and 2.5.0 are exactly the same, so something else must have changed.
@jacobperron @mjcarroll Any insight why this variable would not be used by pybind build?

**Comment by clalancette** [comment]
> Maybe pybind is ignoring it. Seems weird. pybind's `CMakeLists.txt` between 2.2.4 and 2.5.0 are exactly the same, so something else must have changed.

So, just trying to run cmake on both pybind11 2.2.4 and 2.5.0 gives me the same warning on both:
```
cmake .. -DPYBIND11_TEST=OFF -DCMAKE_BUILD_TYPE=Debug

Manually-specified variables were not used by the project:
    CMAKE_BUILD_TYPE
```

So I don't think this is new.  What's odd is that we have this same pattern in other places, like spdlog: https://github.com/ros2/spdlog_vendor/blob/0223d4586fff5863e6d380c38bde5fee46802af7/CMakeLists.txt#L17 .  I'm not particularly sure what is different about pybind11.

**Comment by jacobperron** [comment]
In the case of spdlog, maybe the difference is that the CMakeLists.txt directly references the variable `CMAKE_BUILD_TYPE`? https://github.com/gabime/spdlog/blob/3c527488e7ee2200a6b11beace5476636c52b83b/CMakeLists.txt#L21-L23

**Comment by clalancette** [comment]
Oh, I think I see now.  As far as I can tell, pybind11 is a header-only library.  I think that because of that, there is no target that actually uses the `CMAKE_BUILD_TYPE` variable.

> In the case of spdlog, maybe the difference is that the CMakeLists.txt directly references the variable `CMAKE_BUILD_TYPE`? https://github.com/gabime/spdlog/blob/3c527488e7ee2200a6b11beace5476636c52b83b/CMakeLists.txt#L21-L23

So yeah, I think that is exactly it.  @mabelzhang What I'd suggest here is two things:
1.  Send a patch to upstream pybind11 adding that code.
1.  In the meantime, use our ability to patch the code to add something like what @jacobperron pointed out.  You can get an idea on how to do that by looking at https://github.com/ros2/tinyxml_vendor/blob/master/CMakeLists.txt (there are other uses within the ROS 2 ecosystem as well).

**Comment by dirk-thomas** [comment]
> I think that because of that, there is no target that actually uses the `CMAKE_BUILD_TYPE` variable.

> What I'd suggest here is two things:

Wouldn't it be sufficient then to just remove passing `CMAKE_BUILD_TYPE`?

**Comment by jacobperron** [comment]
Same question as @dirk-thomas. ^

**Comment by mabelzhang** [comment]
This line might be why the warning only happens on Windows:
https://github.com/pybind/pybind11/blob/9a19306fbf30642ca331d0ec88e7da54a96860f9/tools/pybind11Tools.cmake#L191

This file, pybind11Tools.cmake, is included from pybind11 CMakeLists.txt. It's only checking CMAKE_BUILD_TYPE if MSVC is not defined.

The only other file using CMAKE_BUILD_TYPE is tests/CMakeLists.txt, and we aren't building tests.

**Comment by jacobperron** [comment]
I guess continuing to provide CMAKE_BUILD_TYPE could help future-proof this vendor package, if we bump to a newer version of pybind11 that happens to ship with a compiled library.

**Comment by clalancette** [comment]
> > 
> 
> Wouldn't it be sufficient then to just remove passing `CMAKE_BUILD_TYPE`?

Heh, yeah, that is the easier option.

**Comment by mabelzhang** [comment]
Removed passing in `CMAKE_BUILD_TYPE`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11754/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6831/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9589/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11697/)

**Review by dirk-thomas — APPROVED** [review]

**Pull request merged**
